[2022-10-28T19:14:28.828+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T18:05:00+00:00 [queued]>
[2022-10-28T19:14:28.943+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T18:05:00+00:00 [queued]>
[2022-10-28T19:14:28.944+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T19:14:28.944+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-28T19:14:28.944+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T19:14:32.323+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): calculate_hourly_demand_forecast> on 2022-10-26 18:05:00+00:00
[2022-10-28T19:14:32.464+0000] {standard_task_runner.py:55} INFO - Started process 6524 to run task
[2022-10-28T19:14:51.023+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v1', 'calculate_hourly_demand_forecast', 'scheduled__2022-10-26T18:05:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmpd__q80a5']
[2022-10-28T19:14:51.318+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask calculate_hourly_demand_forecast
[2022-10-28T19:15:02.141+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T18:05:00+00:00 [running]> on host f011703e6eb5
[2022-10-28T19:15:05.363+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v1
AIRFLOW_CTX_TASK_ID=calculate_hourly_demand_forecast
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T18:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T18:05:00+00:00
[2022-10-28T19:15:05.399+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-28T19:15:05.422+0000] {logging_mixin.py:120} INFO - INFO calculate_hourly_demand_forecast execution init:  2022-10-26T18:05:00+00:00
[2022-10-28T19:15:05.423+0000] {logging_mixin.py:120} INFO - WORKDIR: /opt/***
[2022-10-28T19:15:05.568+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-28T19:15:05.604+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 1
[2022-10-28T19:15:05.623+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 49
[2022-10-28T19:15:38.296+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-10-28T19:15:38.310+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 6524. PIDs of all processes in the group: [6524]
[2022-10-28T19:15:38.310+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 6524
[2022-10-28T19:15:38.315+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-28T19:15:38.478+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ENG_hourly_process_dag.py", line 63, in calculate_hourly_demand_forecast
    , port=port, n_lookback=48, n_forecast=24, verbose=True)
  File "/opt/airflow/dags/energy.py", line 236, in _calculate_hourly_demand_forecast
    model = load_model('/opt/airflow/dags/lstm_24_model.h5')
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Exception encountered when calling layer "lstm_1" (type LSTM).

Task received SIGTERM signal

Call arguments received by layer "lstm_1" (type LSTM):
  • inputs=tf.Tensor(shape=(None, 48, 50), dtype=float32)
  • mask=None
  • training=None
  • initial_state=None
[2022-10-28T19:15:38.875+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ENG_hourly_process_v1, task_id=calculate_hourly_demand_forecast, execution_date=20221026T180500, start_date=20221028T191428, end_date=20221028T191538
[2022-10-28T19:15:38.985+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 104 for task calculate_hourly_demand_forecast (Exception encountered when calling layer "lstm_1" (type LSTM).

Task received SIGTERM signal

Call arguments received by layer "lstm_1" (type LSTM):
  • inputs=tf.Tensor(shape=(None, 48, 50), dtype=float32)
  • mask=None
  • training=None
  • initial_state=None; 6524)
[2022-10-28T19:15:39.082+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=6524, status='terminated', exitcode=1, started='19:14:32') (6524) terminated with exit code 1
[2022-10-29T00:36:33.649+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T18:05:00+00:00 [queued]>
[2022-10-29T00:36:33.724+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T18:05:00+00:00 [queued]>
[2022-10-29T00:36:33.725+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-29T00:36:33.725+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-29T00:36:33.726+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-29T00:36:33.824+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): calculate_hourly_demand_forecast> on 2022-10-26 18:05:00+00:00
[2022-10-29T00:36:33.836+0000] {standard_task_runner.py:55} INFO - Started process 950 to run task
[2022-10-29T00:36:33.862+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v1', 'calculate_hourly_demand_forecast', 'scheduled__2022-10-26T18:05:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmpt6qus40i']
[2022-10-29T00:36:33.899+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask calculate_hourly_demand_forecast
[2022-10-29T00:36:34.248+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T18:05:00+00:00 [running]> on host 6800cd8e39a3
[2022-10-29T00:36:34.944+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v1
AIRFLOW_CTX_TASK_ID=calculate_hourly_demand_forecast
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T18:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T18:05:00+00:00
[2022-10-29T00:36:34.987+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-29T00:36:34.997+0000] {logging_mixin.py:120} INFO - INFO calculate_hourly_demand_forecast execution init:  2022-10-26T18:05:00+00:00
[2022-10-29T00:36:34.998+0000] {logging_mixin.py:120} INFO - WORKDIR: /opt/***
[2022-10-29T00:36:35.066+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-29T00:36:35.087+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 1
[2022-10-29T00:36:35.130+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 48
[2022-10-29T00:36:54.146+0000] {logging_mixin.py:120} INFO - 1/1 [==============================] - ETA: 0s
[2022-10-29T00:36:54.147+0000] {logging_mixin.py:120} INFO - 1/1 [==============================] - 11s 11s/step
[2022-10-29T00:36:54.158+0000] {logging_mixin.py:120} INFO - INFO _calculate_hourly_demand_forecast: forecast calculated for next 24 hours. Since: 2022-10-28 00:00
[2022-10-29T00:37:03.255+0000] {logging_mixin.py:120} INFO - INFO _calculate_hourly_demand_forecast - 24 records were upserted. Table cammesa_db.hourly_demand_forecast.
[2022-10-29T00:37:03.258+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-10-29T00:37:03.295+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=ENG_hourly_process_v1, task_id=calculate_hourly_demand_forecast, execution_date=20221026T180500, start_date=20221029T003633, end_date=20221029T003703
[2022-10-29T00:37:03.409+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-29T00:37:03.629+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
